### ISSUE TITLE
Error: Inappropriate ioctl for device (os error 25) when starting cloudflared in Docker

### ISSUE THREAD

**Issue by hotwa** [ryoppippi/curxy#13]
## Problem
I'm encountering an error when running `curxy` in a Docker container. The issue appears when `cloudflared` tries to start and fails with the following error:

`Listening on http://127.0.0.1:42291/
◐ Starting cloudflared tunnel to http://127.0.0.1:42291

🔥 Your installation of cloudflared software constitutes a symbol of your signature
   indicating that you accept the terms of the Cloudflare License, Terms and Privacy Policy.

❯ License:         https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/license/
❯ Terms:           https://www.cloudflare.com/terms/
❯ Privacy Policy:  https://www.cloudflare.com/privacypolicy/

error: Uncaught (in promise) Error: Inappropriate ioctl for device (os error 25)
    at Object.consoleSize (ext:runtime/40_tty.js:14:3)
    at new WriteStream (node:tty:76:36)
    at sD.prompt (file:///deno-dir/npm/registry.npmjs.org/consola/3.2.3/dist/chunks/prompt.mjs:141:676)
    at confirm (file:///deno-dir/npm/registry.npmjs.org/consola/3.2.3/dist/chunks/prompt.mjs:251:6)
    at Module.prompt (file:///deno-dir/npm/registry.npmjs.org/consola/3.2.3/dist/chunks/prompt.mjs:404:18)
    at file:///deno-dir/npm/registry.npmjs.org/consola/3.2.3/dist/shared/consola.36c0034f.mjs:617:71
    at async startTunnel (file:///deno-dir/npm/registry.npmjs.org/untun/0.1.3/dist/index.mjs:15:101)
    at async Promise.all (index 1)
    at async https://jsr.io/@ryoppippi/curxy/0.1.5/main.ts:73:3`

**Comment by ryoppippi** [comment]
it is `cloudflared` problem. Report it to them.
Also, why you need to use docker? just download deno runtime and run it

**Comment by ryoppippi** [comment]
I added a flag to disable cloudflare tunnel

**Comment by ryoppippi** [comment]
@hotwa Hey, still any issue? 
If solved, close this issue

**Comment by ryoppippi** [comment]
@hotwa Hey, still any issue?
If solved, close this issue

I fixed it for you. No response?
