### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by drunkenQCat** [ryoppippi/curxy#6]
After run `deno run -A jsr:@ryoppippi/curxy`, the terminal feedback:
```
Listening on http://127.0.0.1:63263/
◐ Starting cloudflared tunnel to http://127.0.0.1:63263                                                 10:44:19
error: Uncaught (in promise) TypeError: Windows only supports ctrl-c (SIGINT) and ctrl-break (SIGBREAK).
    at bindSignal (ext:runtime/40_signals.js:14:10)
    at Object.addSignalListener (ext:runtime/40_signals.js:54:19)
    at Process.on (node:process:355:12)
    at Process.once (ext:deno_node/_events.mjs:533:8)
    at startTunnel (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmmirror.com/untun/0.1.3/dist/index.mjs:36:13)
    at async Promise.all (index 1)
    at async https://jsr.io/@ryoppippi/curxy/0.1.5/main.ts:73:3
    ```

**Comment by ryoppippi** [comment]
I don't use windows so prs are welcome

**Comment by ekinertac** [comment]
just sent a PR

**Comment by ryoppippi** [comment]
@ekinertac hasn't update his PR for a while.
If anyone want to contribute it, I'm happy about it

**Comment by ekinertac** [comment]
couldn't find time to update the PR, all contributions are welcome

**Comment by ryoppippi** [comment]
@ekinertac thank you for your initial work!

**Comment by hgoona** [comment]
Hi @ryoppippi ! Is this now able to be used on Windows or is it still not setup?🤔 I'm new to this kind of thing and just came across your package..

**Comment by hgoona** [comment]
@ryoppippi Oh - how do make that change? 
Im trying it now and I see this if i run `deno run -A jsr:@ryoppippi/curxy`
![image](https://github.com/user-attachments/assets/62c7cf26-8bc7-4d2f-8f1b-186300543a16)

**Comment by ryoppippi** [comment]
I already added `cloudflared` flag, so you can just run `deno run -A jsr:@ryoppippi/curxy --cloudflared=false`
But in this case, the localhost will not be public and you need to find some other way to make it public(maybe using ngrok is another option?)

**Comment by ryoppippi** [comment]
untun is widly used like nuxt or slidev, so idk why it does not work in deno.
If it doesn't work on deno but on node, maybe we re-implement it to use node/bun instead of deno

**Comment by ryoppippi** [comment]
@Joseph-Youngquist thanks! so overall, it is because of deno's problem?
If so, I should stop using deno and move to node or bun

**Comment by BradKML** [comment]
Can someone run an updated documentation on how this is can be used? Also saying hello and crossing from https://github.com/danilofalcao/cursor-deepseek/issues/30

**Comment by ryoppippi** [comment]
@BradKML contributions are welcome. I don't know the cursor-deepseek actually
